FROM osixia/openldap:1.5.0

COPY bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
COPY users.ldif /container/service/slapd/assets/config/bootstrap/ldif/60-users.ldif
