name: CI/CD LDAP Infraestructura

on:
  workflow_dispatch:

jobs:
  despliegue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Inicializar Terraform
        run: terraform init

      - name: Plan de Terraform
        run: terraform plan

      - name: Aplicar Terraform
        run: terraform apply -auto-approve

      - name: Crear clave privada claveuno.pem
        run: |
          echo "${{ secrets.EC2_SSH_KEY_CLAVEUNO }}" > claveuno.pem
          chmod 600 claveuno.pem

      - name: Crear clave privada clavedos.pem
        run: |
          echo "${{ secrets.EC2_SSH_KEY_CLAVEDOS }}" > clavedos.pem
          chmod 600 clavedos.pem

      - name: Subir archivos .cer al servidor web
        run: |
          scp -o StrictHostKeyChecking=no -i claveuno.pem miapp-docker/*.cer ec2-user@54.165.40.6:/tmp/

      - name: Subir archivos .key al servidor web
        run: |
          scp -o StrictHostKeyChecking=no -i claveuno.pem miapp-docker/*.key ec2-user@54.165.40.6:/tmp/

      - name: Subir clavedos.pem a la instancia
        run: |
          scp -o StrictHostKeyChecking=no -i claveuno.pem clavedos.pem ec2-user@54.165.40.6:/home/ec2-user/

      - name: Configurar SSL en Apache en la instancia
        run: |
          ssh -o StrictHostKeyChecking=no -i claveuno.pem ec2-user@54.165.40.6 << 'EOF'
            sudo mkdir -p /etc/ssl/andres/
            sudo mv /tmp/*.cer /etc/ssl/andres/
            sudo mv /tmp/*.key /etc/ssl/andres/
            
          EOF
